server:
 port: 10000
 servlet:
    context-path: /consumer
spring:
  application:
    name: rabbitmq_consumer
  rabbitmq:
    addresses: 192.168.1.8:5672
    username: rabbitmq_admin
    password: 123456
    virtual-host: /test
    connection-timeout: 5000
    listener:
       simple:
          acknowledge-mode: manual
          concurrency: 5
          max-concurrency: 10
          # 超过最大重试次数后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
          default-requeue-rejected: false
          retry:
             # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
             enabled: true
             # 最大重试次数
             #到达5次之后会抛出异常调用MessageRecoverer
             #.默认的实现为RejectAndDontRequeueRecoverer,也就是打印异常，发送nack,不会重新入队列
             max-attempts: 5
             # 重试间隔时间（单位毫秒）
             initial-interval: 3000
             # 重试最大时间间隔（单位毫秒）
             max-interval: 3600000
             # 应用于前一重试间隔的乘法器。当前时间间隔=上次重试间隔*multiplier
             multiplier: 2 # 乘子
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,config
      filter:
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis:  4
      connection-properties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=3000
#      connection-properties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=3000;config.decrypt=true;config.decrypt.key=${spring.datasource.public-key}
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        profile-enable: true
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
        allow: ""
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
    root: INFO
  pattern:
    console:  '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} - ${PID} - [%thread] - %-5level - %logger{50} - %msg%n'
  file:
    path: '${LOG_PATH: /service/logs/rabbitmq_consumer/}'
    max-history: 30
    max-size: 1MB
